package com.lgeek.app.dao;

import java.io.Serializable;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_id
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    private String uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_name
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    private String uName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_password
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    private String uPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_phone
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    private String uPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_email
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    private String uEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_address
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    private String uAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_age
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    private Integer uAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_sex
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    private String uSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_money
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    private Integer uMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_idcart
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    private String uIdcart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_position
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    private String uPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.p_id
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.s_id
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    private Integer sId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_id
     *
     * @return the value of user.u_id
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public String getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_id
     *
     * @param uId the value for user.u_id
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public void setuId(String uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_name
     *
     * @return the value of user.u_name
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_name
     *
     * @param uName the value for user.u_name
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public void setuName(String uName) {
        this.uName = uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_password
     *
     * @return the value of user.u_password
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public String getuPassword() {
        return uPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_password
     *
     * @param uPassword the value for user.u_password
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public void setuPassword(String uPassword) {
        this.uPassword = uPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_phone
     *
     * @return the value of user.u_phone
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public String getuPhone() {
        return uPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_phone
     *
     * @param uPhone the value for user.u_phone
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public void setuPhone(String uPhone) {
        this.uPhone = uPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_email
     *
     * @return the value of user.u_email
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public String getuEmail() {
        return uEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_email
     *
     * @param uEmail the value for user.u_email
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public void setuEmail(String uEmail) {
        this.uEmail = uEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_address
     *
     * @return the value of user.u_address
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public String getuAddress() {
        return uAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_address
     *
     * @param uAddress the value for user.u_address
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public void setuAddress(String uAddress) {
        this.uAddress = uAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_age
     *
     * @return the value of user.u_age
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public Integer getuAge() {
        return uAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_age
     *
     * @param uAge the value for user.u_age
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public void setuAge(Integer uAge) {
        this.uAge = uAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_sex
     *
     * @return the value of user.u_sex
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public String getuSex() {
        return uSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_sex
     *
     * @param uSex the value for user.u_sex
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public void setuSex(String uSex) {
        this.uSex = uSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_money
     *
     * @return the value of user.u_money
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public Integer getuMoney() {
        return uMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_money
     *
     * @param uMoney the value for user.u_money
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public void setuMoney(Integer uMoney) {
        this.uMoney = uMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_idcart
     *
     * @return the value of user.u_idcart
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public String getuIdcart() {
        return uIdcart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_idcart
     *
     * @param uIdcart the value for user.u_idcart
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public void setuIdcart(String uIdcart) {
        this.uIdcart = uIdcart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_position
     *
     * @return the value of user.u_position
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public String getuPosition() {
        return uPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_position
     *
     * @param uPosition the value for user.u_position
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public void setuPosition(String uPosition) {
        this.uPosition = uPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.p_id
     *
     * @return the value of user.p_id
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.p_id
     *
     * @param pId the value for user.p_id
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.s_id
     *
     * @return the value of user.s_id
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.s_id
     *
     * @param sId the value for user.s_id
     *
     * @mbg.generated Fri Jun 01 14:11:40 CST 2018
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }
}